/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Enemy } from "./Enemy";
import { EnemyCountArgs } from "./EnemyCountArgs";
import { EnemyFindManyArgs } from "./EnemyFindManyArgs";
import { EnemyFindUniqueArgs } from "./EnemyFindUniqueArgs";
import { DeleteEnemyArgs } from "./DeleteEnemyArgs";
import { EnemyService } from "../enemy.service";
@graphql.Resolver(() => Enemy)
export class EnemyResolverBase {
  constructor(protected readonly service: EnemyService) {}

  async _enemiesMeta(
    @graphql.Args() args: EnemyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Enemy])
  async enemies(@graphql.Args() args: EnemyFindManyArgs): Promise<Enemy[]> {
    return this.service.enemies(args);
  }

  @graphql.Query(() => Enemy, { nullable: true })
  async enemy(
    @graphql.Args() args: EnemyFindUniqueArgs
  ): Promise<Enemy | null> {
    const result = await this.service.enemy(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Enemy)
  async deleteEnemy(
    @graphql.Args() args: DeleteEnemyArgs
  ): Promise<Enemy | null> {
    try {
      return await this.service.deleteEnemy(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
